version: '2'
services:
    jhng20180924-app:
        image: jhng20180924
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://jhng20180924-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhng20180924
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhng20180924-mongodb:
        extends:
            file: mongodb.yml
            service: jhng20180924-mongodb
